- name: Update fullstack to a specific intermediate revision
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    disable_edx_services: true
    mongo_enable_journal: false
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    EDXAPP_MONGO_HOSTS: ['10.0.1.232']
    EDXAPP_MYSQL_HOST: '10.0.1.232'
    XQUEUE_MYSQL_HOST: '10.0.1.232'
  roles:
    - common
    - vhost
    - edxapp
    - xqueue
    - role: edxlocal
      when: EDXAPP_MYSQL_HOST == 'localhost'
